---
title: "Heming 2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
4*12

```
```{r}
mean (4, 6, 8, 5, 6, 7, 7, 7)
```
```{r}
x<-42
print(x)
```
```{r}
x<-20
y<-30
z<-x+y
z
```
```{r}
venom_GT <- 270
chiron <- 261
veyron <- 268
(270+261+268)/3
```
```{r}
my_numeric <- 42
my_integer <- 2L #adding an L automatically denotes an integer
my_character <- "universe"
my_logical <- FALSE
my_complex <- 2+4i
class(my_numeric)
is.integer(my_numeric) 
my_integer <- as.integer(my_numeric)
is.integer(my_integer)

```
```{r}
new_vector <- 1:100
new_vector == 15
```
```{r}
new_vector[new_vector <= 10 | new_vector == 12]
```
```{r}
library(tidyverse)
options(scipen=999)
organism <- c("Human","Mouse", "Fruit Fly", "Roudworm", "Yeast")
genomeSizeBP <- c(3000000000, 3000000000, 135600000, 97000000, 12100000)
estGeneCount <- c(30000, 30000, 13061, 19099, 6034)
comparativeGenomeSize <- data.frame(organism=organism, genomeSizeBP=genomeSizeBP, estGeneCount=estGeneCount)
comparativeGenomeSize

```
